---
format: gfm
engine: knitr
embed-resources: true
---

# gdocker

`gdocker` is a command-line tool written in Go for managing and building Docker images, especially for bioinformatics tools.
It provides commands to show image dependencies, build images with dependency resolution, run containers with preset options, and manage image directories.
The tool supports features like visualizing dependency graphs, exporting build instructions, and preparing templates for new images.

## Install

Before installing `gdocker`, ensure the following are installed on your system:

- git
- Go
- make
- docker

To install `gdocker`, run the following command in terminal:

```{bash}
#| eval: false
go install github.com/t-arae/gdocker@latest
```

## main commmand 

To see the available commands and global options, run:

```{bash}
gdocker --help
```

This will display a list of all supported subcommands and their descriptions.
For help with a specific subcommand, use:

```{bash}
#| eval: false
gdocker help <subcommand>
```

Replace <subcommand> with the name of the command you want help with (e.g., build, showdeps, run).
